# Generated by Django 5.2.5 on 2025-08-23 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Название главы")),
                ("description", models.TextField(blank=True, verbose_name="Описание главы")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="series_covers/", verbose_name="Изображение главы"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор главы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Глава",
                "verbose_name_plural": "Главыы",
            },
        ),
        migrations.AlterField(
            model_name="posts",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="posts.chapter",
                verbose_name="Глава",
            ),
        ),
        migrations.DeleteModel(
            name="Series",
        ),
    ]
