# Generated by Django 5.2.5 on 2025-08-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_chapter_alter_post_series_delete_series"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={"verbose_name": "Глава", "verbose_name_plural": "Главы"},
        ),
    ]
