# Generated by Django 5.2.5 on 2025-08-26 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_remove_post_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="series",
            new_name="chapter",
        ),
    ]
