# Generated by Django 5.2.5 on 2025-08-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_rename_series_post_chapter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["sequence_number"], "verbose_name": "Пост", "verbose_name_plural": "Посты"},
        ),
        migrations.RemoveField(
            model_name="post",
            name="sequence_order",
        ),
        migrations.AddField(
            model_name="post",
            name="sequence_number",
            field=models.PositiveIntegerField(default=1, verbose_name="Номер поста в главе"),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(blank=True, verbose_name="Содержание поста"),
        ),
    ]
