# Generated by Django 5.2.5 on 2025-08-26 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_post_options_remove_post_sequence_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="chapter",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="posts.chapter",
                verbose_name="Глава",
            ),
        ),
    ]
