# Generated by Django 5.2.5 on 2025-08-26 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_post_chapter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="posts.chapter",
                verbose_name="Глава",
            ),
        ),
    ]
