# Generated by Django 5.2.5 on 2025-08-27 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_alter_post_chapter"),
        ("users", "0005_remove_payment_paid_chapter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="chapter",
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Пост", "verbose_name_plural": "Посты"},
        ),
        migrations.RemoveField(
            model_name="post",
            name="sequence_number",
        ),
        migrations.DeleteModel(
            name="Chapter",
        ),
    ]
