# Generated by Django 5.2.5 on 2025-08-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_remove_post_chapter_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="media_type",
            field=models.CharField(
                choices=[("TEXT", "Текстовый пост"), ("VIDEO", "Видео")], default="TEXT", max_length=10
            ),
        ),
    ]
