# Generated by Django 5.2.5 on 2025-08-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0011_alter_post_media_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="media_type",
            field=models.CharField(choices=[("VIDEO", "Видео"), ("IMAGE", "Изображение")], max_length=50),
        ),
    ]
