# Generated by Django 5.2.5 on 2025-08-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0013_alter_post_media_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="media_type",
            field=models.CharField(
                blank=True,
                choices=[("VIDEO", "Видео"), ("IMAGE", "Изображение")],
                default="TEXT",
                max_length=50,
                null=True,
            ),
        ),
    ]
