# Generated by Django 5.2.5 on 2025-08-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0014_alter_post_media_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="media_type",
        ),
    ]
