# Generated by Django 5.2.5 on 2025-08-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0015_remove_post_media_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={},
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="subscribed_at",
            new_name="starts_at",
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="subscriber",
            new_name="user",
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="post",
            name="price",
        ),
        migrations.AddField(
            model_name="subscription",
            name="ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name="Стоимость подписки"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="subscription_level",
            field=models.CharField(choices=[("SINGLE", "Разовая подписка")], default="SINGLE", max_length=50),
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="author",
        ),
    ]
