# Generated by Django 5.2.5 on 2025-08-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0016_alter_subscription_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={"verbose_name": "Подписка", "verbose_name_plural": "Подписки"},
        ),
        migrations.AlterField(
            model_name="subscription",
            name="active",
            field=models.BooleanField(default=False, verbose_name="Статус активности"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="ends_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата окончания подписки"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="starts_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата начала подписки"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscription_level",
            field=models.CharField(
                choices=[("SINGLE", "Разовая подписка")],
                default="SINGLE",
                max_length=50,
                verbose_name="Уровень подписки",
            ),
        ),
    ]
