# Generated by Django 5.2.5 on 2025-08-25 16:30

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_remove_post_content"),
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payment_date", models.DateTimeField(default=datetime.datetime.now, verbose_name="Дата платежа")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Сумма оплаты")),
                (
                    "method",
                    models.CharField(
                        choices=[("cash", "Наличные"), ("transfer", "Перевод на счёт")],
                        default="cash",
                        max_length=10,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "stripe_payment_id",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="ID платежа в Stripe"),
                ),
                (
                    "link_payment",
                    models.URLField(blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"),
                ),
                (
                    "paid_chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="posts.chapter",
                        verbose_name="Оплаченный курс/блок",
                    ),
                ),
                (
                    "paid_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="posts.post",
                        verbose_name="Отдельно оплаченный пост",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёж",
                "verbose_name_plural": "Платежи",
            },
        ),
    ]
