# Generated by Django 5.2.5 on 2025-08-27 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_payment_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="paid_chapter",
        ),
    ]
