# Generated by Django 5.2.5 on 2025-08-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_payment_paid_chapter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счёт")],
                default="cash",
                max_length=50,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
