# Generated by Django 5.2.5 on 2025-08-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription_status",
            field=models.BooleanField(default=False, verbose_name="Подписался"),
        ),
    ]
