# Generated by Django 5.2.5 on 2025-08-30 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_subscription_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="subscription_status",
        ),
    ]
