# Generated by Django 5.2.5 on 2025-08-30 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0017_alter_subscription_options_alter_subscription_active_and_more"),
        ("users", "0008_remove_user_subscription_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="paid_post",
        ),
        migrations.AddField(
            model_name="payment",
            name="paid_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="posts.subscription",
                verbose_name="Оплата подписки",
            ),
        ),
    ]
