# Generated by Django 5.2.5 on 2025-10-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_payment_paid_post_payment_paid_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link_payment",
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name="Ссылка на оплату"),
        ),
    ]
